### ISSUE TITLE
API document not correct

### ISSUE THREAD

**Issue by viko16** [lukeed/matchit#2]
`matchit.exec(url, match)` actually return the `params` object
![image](https://user-images.githubusercontent.com/5064777/35183712-7add11f2-fe25-11e7-8635-a7ab51e4d76e.png)

https://repl.it/@viko16/try-matchit-online

**Comment by lukeed** [comment]
Closed via 88ae85e696041c5df3c2525d6d1ea1890cd3f0fc, thanks!
