### ISSUE TITLE
Use with webpack / rollup

### ISSUE THREAD

**Issue by egoist** [lukeed/matchit#5]
Webpack/Rollup will use the es module version of `@arr/every` `@arr/filter`, so `require('@arr/every')()` would break unless you call `require('..').default()` instead.

**Comment by egoist** [comment]
It's tricky for users to fix this on their side, maybe you can bundle this library with Rollup and use es import: `import every from '@arr/every'` to let Rollup wrap it in a `interopDefault` function?

**Comment by lukeed** [comment]
Odd. I'm using matchit inside webpack and roll-up projects right now and it's fine. But you're right, I'll add a module version of this library so that it's consistent all the way through.

**Comment by lukeed** [comment]
Added a `module` field to the package in `1.0.2`~! 

That export uses `import` statements for the `@arr` deps. This will force any bundler that _already_ picks up `module` fields to continue doing so, applying its own interop to the `@arr` dependencies.

Thanks for the heads up!
