### ISSUE TITLE
Optional param not working

### ISSUE THREAD

**Issue by thomasdigby** [lukeed/matchit#8]
I'm running into a few issues with optional params in the middle of my paths, I used `path-to-regexp` previously and `/test/:baz?/test` matched `/test/test`, whereas `matchit` doesn't match.

I've created a minimal test-case [here](https://jsbin.com/xuxajiqaqe/edit?js,console) with `matchit` 1.0.6, hope that's useful.

**Comment by lukeed** [comment]
Hey~! 

That's actually by design, but mostly because I've _never_ seen this use case in however many years haha. TBH, I likely won't support it (sorry!), but out of curiosity, what are the actual URLs?

**Comment by jonsherrard** [comment]
Chiming in:

/:category/:optional-subcategory?/:post-slug

**Comment by thomasdigby** [comment]
Thanks Luke, as Jon said we've got an optional subcategory on a route mid-way through the URL. I _think_ this is the Wordpress default routing structure (in PHP).

We've defined our routes to be unambiguous so there's no possibility it would clash with other URLs.
